site_name: Professor Sathish Academy

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.expand
    - navigation.tabs
    - toc.follow
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - content.code.copy
    - content.code.annotate
nav:
  - Home: index.md
  - C Programming: 
    - What is C: C_Prog/01.md
    - Which C are we learning: C_Prog/02.md
    - Getting Started with C: C_Prog/03.md
    - Alphabets,Digits and Special Symbols : C_Prog/04.md
    - Constants,Variables and Keywords : C_Prog/05.md
    - Types of Constants : C_Prog/06.md
    - Rules for Constructing Integer Constants: C_Prog/07.md
    - Rules for Constructing Real Constants: C_Prog/08.md
    - Types of C Variables: C_Prog/09.md
    - Rules for Constructing Variable Names: C_Prog/10.md
    - C Keywords: C_Prog/11.md
    - The First C Program: C_Prog/12.md
    - Form of a C Program: C_Prog/13.md
    - Comments in a C Program: C_Prog/14.md
    - What is main() ?: C_Prog/15.md
    - Variables and their usage: C_Prog/16.md
    - printf() and its purpose: C_Prog/17.md
    - Compilation and Execution: C_Prog/18.md
    - Receiving Input: C_Prog/19.md
    - Programs for practice : C_Prog/20.md
    

extra:
  generator: false
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.critic:
      mode: view
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
